/**
 * Generates docs/conformance.md: every automatic W3C test, run in both data
 * models, plus the manual verdicts and the deviations. Deterministic (virtual
 * time, no timestamps), so CI can check the committed report is current.
 *
 *   bun scripts/docs/conformance-report.ts          write docs/conformance.md  (mise run docs:conformance)
 *   bun scripts/docs/conformance-report.ts --check  fail if it would change    (scripts/ci)
 */
import { join } from "node:path";
import { type Entry, manifest, type Outcome, runTest } from "../../conformance/harness.ts";
import { BLOB } from "./config.ts";
import { ROOT } from "./markdown.ts";

const OUT = join(ROOT, "docs/conformance.md");
const check = process.argv.includes("--check");

/** Optional tests that fail by design: they need the Basic HTTP Event I/O Processor (spec C.2), which isn't included. */
const HTTP_TESTS = new Set(["201", "509", "510", "518", "519", "520", "522", "531", "532", "534", "567", "577"]);
const HTTP = "needs the Basic HTTP Event I/O Processor, which isn't included";

type Row = Entry & { specnum: string; sandboxed: Outcome; trusted: Outcome };
const rows: Row[] = [];
for (const e of manifest as (Entry & { specnum: string })[]) {
  if (e.manual) continue;
  const [s, t] = [await runTest(e, false), await runTest(e, true)];
  rows.push({ ...e, sandboxed: s.outcome, trusted: t.outcome });
}

const count = (c: "mandatory" | "optional", mode: "sandboxed" | "trusted") =>
  `${rows.filter((r) => r.conformance === c && r[mode] === "pass").length}/${rows.filter((r) => r.conformance === c).length}`;
const mark = (o: Outcome) => (o === "pass" ? "pass" : `**${o}**`);
const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
const short = (s: string, n = 150) => (s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s);
const bySection = (a: Row, b: Row) => {
  const key = (r: Row) => r.specnum.split(".").map((p) => (/^\d+$/.test(p) ? p.padStart(3, "0") : p));
  const [ka, kb] = [key(a), key(b)];
  for (let i = 0; i < Math.max(ka.length, kb.length); i++) if (ka[i] !== kb[i]) return (ka[i] ?? "").localeCompare(kb[i] ?? "");
  return Number.parseInt(a.id, 10) - Number.parseInt(b.id, 10) || a.id.localeCompare(b.id);
};
const failing = rows.filter((r) => r.sandboxed !== "pass" || r.trusted !== "pass");
const unexplained = failing.filter((r) => r.conformance === "mandatory" || !HTTP_TESTS.has(r.id));

const md = `# Conformance

<!-- Generated by \`mise run docs:conformance\` (scripts/docs/conformance-report.ts). Don't edit by hand. -->

The interpreter is tested against the W3C [SCXML 1.0 Implementation Report Plan](https://www.w3.org/Voice/2013/scxml-irp/)
test suite, converted to the ECMAScript data model. The converted suite is vendored in
[\`conformance/\`](${BLOB}/conformance) (W3C licence in [\`conformance/LICENSE-W3C\`](${BLOB}/conformance/LICENSE-W3C)), so running it needs no network.
A test passes when its session reaches the top-level \`<final id="pass">\`. Time is virtual, so delayed events
fire instantly and the whole suite runs in well under a second per data model.

Reproduce: \`mise run conformance\` (sandboxed), \`mise run conformance:trusted\` (trusted),
\`mise run docs:conformance\` (this page). \`bun test\` runs the suite too, in both data models.

## Summary

| | Sandboxed (QuickJS) | Trusted (host engine) |
|---|---|---|
| Mandatory tests | **${count("mandatory", "sandboxed")}** | **${count("mandatory", "trusted")}** |
| Optional tests | ${count("optional", "sandboxed")} | ${count("optional", "trusted")} |
| Manual tests | see [below](#manual-tests) | see [below](#manual-tests) |

${
  failing.length
    ? `Every test that doesn't pass is optional and ${HTTP}:
${failing
  .sort(bySection)
  .map((r) => `[${r.id}](${BLOB}/${join("conformance", r.file)})`)
  .join(", ")}. See [deviations](deviations.md).`
    : "Every automatic test passes."
}

## Manual tests

${manifest.filter((e) => e.manual).length} tests are marked *manual*: a person reads the output and decides. The verdicts, with the
evidence for each, are in [\`conformance/MANUAL.md\`](${BLOB}/conformance/MANUAL.md): 8 pass, and 513 is not
applicable (it needs the Basic HTTP processor). The mechanically checkable ones are also pinned in
\`conformance/conformance.test.ts\`.

## Deviations

Where the interpreter deliberately differs from the specification, or leaves something out, is listed in
[deviations.md](deviations.md), each item pinned by a test.

## All automatic tests

Sorted by specification section. Descriptions are the W3C's, shortened.

| Test | Section | | Sandboxed | Trusted | What it checks |
|---|---|---|---|---|---|
${rows
  .sort(bySection)
  .map(
    (r) =>
      `| [${r.id}](${BLOB}/${join("conformance", r.file)}) | ${r.specnum} | ${r.conformance === "mandatory" ? "M" : "O"} | ${mark(r.sandboxed)} | ${mark(r.trusted)} | ${cell(short(r.description))} |`,
  )
  .join("\n")}

M = mandatory, O = optional.
`;

if (unexplained.length) {
  console.error(`unexpected failures (mandatory, or optional but not Basic HTTP): ${unexplained.map((r) => r.id).join(", ")}`);
  process.exit(1);
}
if (check) {
  const current = (await Bun.file(OUT).exists()) ? await Bun.file(OUT).text() : "";
  if (current !== md) {
    console.error("docs/conformance.md is out of date: run `mise run docs:conformance`");
    process.exit(1);
  }
  console.log("✓ docs/conformance.md is current");
} else {
  await Bun.write(OUT, md);
  console.log(
    `wrote docs/conformance.md (${rows.length} tests; mandatory ${count("mandatory", "sandboxed")} / ${count("mandatory", "trusted")})`,
  );
}
process.exit(0);
