/**
 * Publishes recorded README media (run by scripts/readme-media after recording and encoding).
 *
 *   bun scripts/media/publish.ts --work <dir> [--no-upload] [--no-commit]
 *
 * <dir> holds explorer.webm, explorer.webp and explorer.png. This:
 *   1. names them explorer-<hash8>.* (hash of the video) so README links change with the media;
 *   2. pushes them to the orphan branch `readme-media` as a single squashed commit that keeps the
 *      newest two sets (links from the previous README keep working until the next refresh);
 *   3. rewrites the media block between the markers in the READMEs;
 *   4. commits only the READMEs and pushes the current branch.
 * In GitHub Actions the commit is made as github-actions[bot]; locally with your git identity.
 */
import { copyFile, mkdtemp, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { $ } from "bun";
import { MEDIA, MEDIA_BRANCH, MEDIA_END, MEDIA_READMES, MEDIA_START } from "../docs/config.ts";

const root = join(import.meta.dir, "../..");
const argv = process.argv.slice(2);
const work = argv[argv.indexOf("--work") + 1];
const upload = !argv.includes("--no-upload");
const commit = upload && !argv.includes("--no-commit");
if (!argv.includes("--work") || !work) throw new Error("usage: publish.ts --work <dir> [--no-upload] [--no-commit]");
const ci = process.env.GITHUB_ACTIONS === "true";
const KEEP = 2; // media sets kept on the branch
const EXTS = ["webm", "webp", "png"] as const;

const fail = (msg: string): never => {
  console.error(`✗ ${msg}`);
  process.exit(1);
};
const git = (...args: string[]) => $`git ${args}`.cwd(root).quiet();

// ── preconditions ───────────────────────────────────────────────────────────
const dirty = (await git("status", "--porcelain", "--", ...MEDIA_READMES).text()).trim();
if (dirty) fail(`uncommitted changes in the READMEs; commit or stash them first:\n${dirty}`);
for (const f of MEDIA_READMES) {
  const text = await Bun.file(join(root, f)).text();
  if (!text.includes(MEDIA_START) || !text.includes(MEDIA_END)) fail(`${f} has no ${MEDIA_START} … ${MEDIA_END} block`);
}
if (upload && !ci && (await $`gh auth status`.quiet().nothrow()).exitCode !== 0) fail("gh isn't authenticated (gh auth login)");

// ── name the set ────────────────────────────────────────────────────────────
const video = await Bun.file(join(work, "explorer.webm")).arrayBuffer();
const hash = new Bun.CryptoHasher("sha256").update(video).digest("hex").slice(0, 8);
const names = Object.fromEntries(EXTS.map((ext) => [ext, `explorer-${hash}.${ext}`])) as Record<(typeof EXTS)[number], string>;
const current = (await Bun.file(join(root, MEDIA_READMES[0]!)).text()).match(/explorer-([0-9a-f]{8})\.webp/)?.[1];
console.log(`media set ${hash}${current ? ` (README currently shows ${current})` : ""}`);
if (current === hash) {
  console.log("✓ the READMEs already show this media: nothing to do");
  process.exit(0);
}
if (!upload) {
  console.log("--no-upload: stopping before any change");
  process.exit(0);
}

// ── the media branch: one squashed commit with the newest KEEP sets ─────────
const tree = await mkdtemp(join(tmpdir(), "readme-media-branch-"));
const existing = (await git("ls-remote", "--heads", "origin", MEDIA_BRANCH).text()).trim() !== "";
try {
  if (existing) {
    await git("fetch", "--quiet", "--depth=1", "origin", MEDIA_BRANCH);
    await git("worktree", "add", "--quiet", "--detach", tree, "FETCH_HEAD");
  } else {
    await git("worktree", "add", "--quiet", "--detach", tree, "HEAD");
    await $`git rm -r -q --cached .`.cwd(tree).quiet();
    for (const entry of await readdir(tree)) if (entry !== ".git") await rm(join(tree, entry), { recursive: true, force: true });
  }
  // sets.json: newest first
  const setsFile = Bun.file(join(tree, "sets.json"));
  const sets: { hash: string; date: string }[] = (await setsFile.exists()) ? await setsFile.json() : [];
  const kept = [{ hash, date: new Date().toISOString() }, ...sets.filter((s) => s.hash !== hash)].slice(0, KEEP);
  for (const entry of await readdir(tree)) {
    const m = entry.match(/^explorer-([0-9a-f]{8})\./);
    if (m && !kept.some((s) => s.hash === m[1])) await rm(join(tree, entry));
  }
  for (const ext of EXTS) await copyFile(join(work, `explorer.${ext}`), join(tree, names[ext]));
  await Bun.write(join(tree, "sets.json"), `${JSON.stringify(kept, null, 2)}\n`);
  await Bun.write(
    join(tree, "README.md"),
    `# README media\n\nGenerated by \`scripts/readme-media\` on \`main\`; don't edit this branch by hand.\nIt's force-pushed as a single commit holding the newest ${KEEP} media sets (see \`sets.json\`).\n`,
  );
  const identity = ci
    ? ["-c", "user.name=github-actions[bot]", "-c", "user.email=41898282+github-actions[bot]@users.noreply.github.com"]
    : [];
  await $`git checkout --quiet --orphan readme-media-publish`.cwd(tree).quiet();
  await $`git add -A`.cwd(tree).quiet();
  await $`git ${identity} commit --quiet -m ${`README media ${hash}`}`.cwd(tree).quiet();
  await $`git push --quiet --force origin HEAD:refs/heads/${MEDIA_BRANCH}`.cwd(tree);
  console.log(`✓ pushed ${EXTS.map((e) => names[e]).join(", ")} to ${MEDIA_BRANCH} (keeping ${kept.map((s) => s.hash).join(", ")})`);
} finally {
  await git("worktree", "remove", "--force", tree).catch(() => {});
  await git("branch", "-D", "readme-media-publish").nothrow();
}

// raw.githubusercontent.com may take a moment to see a new branch head
for (let i = 0; i < 20; i++) {
  const res = await fetch(`${MEDIA}/${names.webp}`, { method: "HEAD" });
  if (res.ok) break;
  await Bun.sleep(3000);
}

// ── the READMEs ─────────────────────────────────────────────────────────────
const block = `${MEDIA_START}
<!-- generated by scripts/readme-media: don't edit by hand -->
[![<scxml-explorer> following a running order-fulfilment system: the order machine's tree, the focus on its current state, the events it accepts, and the System level with the payment and shipment machines](${MEDIA}/${names.webp})](${MEDIA}/${names.webm})

<sub>[Full-resolution video](${MEDIA}/${names.webm}) (WebM, 2880×1800) · [High-resolution screenshot](${MEDIA}/${names.png}) (PNG) · the explorer with the optional Tinyactors theme</sub>
${MEDIA_END}`;
for (const f of MEDIA_READMES) {
  const path = join(root, f);
  const text = await Bun.file(path).text();
  const start = text.indexOf(MEDIA_START);
  const end = text.indexOf(MEDIA_END) + MEDIA_END.length;
  await Bun.write(path, text.slice(0, start) + block + text.slice(end));
}
console.log(`✓ updated ${MEDIA_READMES.join(", ")}`);
if (!commit) {
  console.log("--no-commit: the READMEs are changed but not committed");
  process.exit(0);
}

// ── commit and push only the READMEs ────────────────────────────────────────
const identity = ci
  ? ["-c", "user.name=github-actions[bot]", "-c", "user.email=41898282+github-actions[bot]@users.noreply.github.com"]
  : [];
await git(...identity, "commit", "--quiet", "-m", "docs: refresh README media", "--", ...MEDIA_READMES);
const branch = ci ? process.env.GITHUB_REF_NAME : (await git("branch", "--show-current").text()).trim();
if (!branch) fail("not on a branch: can't push");
await $`git push --quiet origin HEAD:refs/heads/${branch}`.cwd(root);
console.log(`✓ committed and pushed the READMEs to ${branch}`);
